FROM ubuntu

# Install tools
RUN apt-get update
RUN apt-get install -y build-essential cmake wget libunwind8 apt-transport-https gdb

# Install .Net core sdk
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update
RUN apt-get install -y dotnet-sdk-2.2
RUN rm packages-microsoft-prod.deb

# Install ragemp server
RUN wget https://cdn.rage.mp/lin/ragemp-srv-037.tar.gz
RUN tar -xzvf ragemp-srv-037.tar.gz
RUN rm ragemp-srv-037.tar.gz

# Install .Net core clr runtime
WORKDIR /ragemp-srv
RUN mkdir -p dotnet/plugins
RUN mkdir -p dotnet/resources
RUN mkdir -p dotnet/runtime/download
WORKDIR /ragemp-srv/dotnet/runtime/download
RUN wget https://download.visualstudio.microsoft.com/download/pr/21968111-f65e-48c7-9c35-8b40de4af06c/66b7a2c7b92b54bd3311f4509cc9b9ed/dotnet-runtime-2.2.5-linux-x64.tar.gz
RUN tar -zxvf dotnet-runtime-2.2.5-linux-x64.tar.gz
RUN cp shared/Microsoft.NETCore.App/2.2.5/* ../
WORKDIR /ragemp-srv/dotnet/runtime
RUN rm -r download

WORKDIR /ragemp-srv

EXPOSE 22005/udp
EXPOSE 22006/tcp

CMD /bin/bash
